### ISSUE TITLE
YouTube changed API

### ISSUE THREAD

**Issue by czekaj** [czekaj/ChromePlay#1]
YouTube has changed something in their API and MP4 urls are no longer playable, you also cannot download YT videos anymore.

So until figured out YouTube is not supported.

**Comment by poingg** [comment]
Czekaj, did you give up on this?

**Comment by czekaj** [comment]
Short answer is: Yes, I did, @poingg. 

Long answer: YouTube has changed their video delivery process dramatically.
Implementation suggested by @piranha is in Python and is heavily based on video processing which just cannot be done in pure JavaScript. Even if it could be then AppleTV requires an url to the video file or stream. To do that I'd need to implement at least some kind of simple HTTP server (we're still talking pure JS since this is a Chrome extension!). And this is just for starters.
So unless somebody can point me to a straightforward JS-based solution to this problem I will not be trying to fix it myself. But well, guys, this is Github and anyone can take over.
