### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by Alexander-10** [czekaj/ChromePlay#15]
MAC Chrome Version 49.0.2623.87 (64-bit)
Last ChromePlay installed

Nothing happens when i click the icon of ChromePlay.

cheers,
Alex

**Comment by czekaj** [comment]
can you ping your apple tv using the hostname you put in Options menu?

**Comment by Alexander-10** [comment]
good question.. but.. which is the procedure to “ping the apple tv”?   :)

**Comment by czekaj** [comment]
Then the hostname is probably wrong. Please look up how to get Apple TV hostname/ip and then how to ping host/ip on Google. Changing hostname in the extension options should solve your issue.

**Comment by Alexander-10** [comment]
ah ok, thanks.

I’ve found this:
https://discussions.apple.com/thread/4998013?start=0&tstart=0 <https://discussions.apple.com/thread/4998013?start=0&tstart=0>

I just had to put the IP of the Apple TV instead of the name.

best regards, and good work!

Alex

**Comment by czekaj** [comment]
Sure, thanks!
