### ISSUE TITLE
just loading screen 

### ISSUE THREAD

**Issue by blackest** [czekaj/ChromePlay#23]
something isn't quite right it is finding my appletv and it looks like it trys to load but it isn't getting anywhere. i think if it went for a lower bandwidth feed it would perhaps work better. 
My internet connection isn't great.

**Comment by JacopKane** [comment]
Same here with good connection.

**Comment by roumor** [comment]
any way to fix this?

**Comment by Rorzzer** [comment]
bump

**Comment by czekaj** [comment]
Apple changed the AirPlay protocol with tvOS 10. I haven't looked into it too much but it looks like it may be hard to fix ChromePlay.
