### ISSUE TITLE
Cannot read property 'nodeValue' of undefined

### ISSUE THREAD

**Issue by olegafx** [czekaj/ChromePlay#5]
I’m using [React](https://facebook.github.io/react/). And in `render` function I could return `null` to indicate that I don’t want to render anything. In that case React outputs `<noscript data-reactid=".0.0.2"></noscript>`.

And in console I see error `Cannot read property 'nodeValue' of undefined chromeplay_contentscript.js:17`

![smarttracking](https://cloud.githubusercontent.com/assets/867546/8079639/a3666716-0f6e-11e5-9cfa-0cbc67a9e474.png)

**Comment by czekaj** [comment]
Hi @olegafx. 
Can you fix the code and create a pull request? 
It seems very specific to React.
